# -*- coding: utf-8 -*-
"""algoritma vize 2012903058

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kvmKSJ7AxhGtaS1SYPbAqYBGA7OrEdbf

Merhabalar hocam ödevimi çalıştırmak için 2 tane kütüphane gerekiyor.

BeautifulSoup --> pip install BeautifulSoup4

requests ---> pip install requests
"""

import requests
from bs4 import BeautifulSoup
import time

isim = input("Buraya İsminizi Giriniz : ")

liste = []
r = requests.get("http://www.koeri.boun.edu.tr/scripts/lst9.asp")
soup = BeautifulSoup(r.content, "lxml")
depremler = soup.find_all("pre", attrs = {"pre":""})

for kısımlar in depremler: 
  liste.append(kısımlar)

with open("SonDakikaDepremler.txt","w+", encoding = "utf-8") as file:
  for i in liste:
    time.sleep(1)
    print("Veriler dosyaya yazılıyor lütfen bekleyiniz..")
    file.writelines(i)
    time.sleep(2)
    print("Veriler dosyaya yazıldı")
    break

with open("SonDakikaDepremler.txt","r+",encoding = "utf-8") as file2:
  denek_dosya = file2.readlines()

while True:
  tercih = input("yeni veri geldiğini kontrol etmek için herhangi bir tuşa basın 'çıkış için : q' ")
  if (tercih == "q"):
    break
  else:
    print("yeni veriler bekleniyor...")
    time.sleep(60)
    
    
    liste2 = []
    r = requests.get("http://www.koeri.boun.edu.tr/scripts/lst9.asp")
    soup = BeautifulSoup(r.content, "lxml")
    depremler = soup.find_all("pre", attrs = {"pre":""})
    
    for kısımlar in depremler: 
      liste2.append(kısımlar)

    with open("SonDakikaDepremler2.txt","w+", encoding = "utf-8") as file:
      for i in liste:
        file.writelines(i)
  

      with open("SonDakikaDepremler2.txt","r+",encoding = "utf-8") as file3:
        denek_dosya2 = file3.readlines()

    if denek_dosya != denek_dosya2:
      print("veriler güncellendi")
      break
    else:
      print("yeni bir deprem olmadı")
      break

print(isim,"Ödevime baktığın için teşekkür ederim...")
time.sleep(0.9)
print("Hayri Doğuhan Korkmaz 2012903058")

with open("SonDakikaDepremler.txt","r", encoding = "utf-8") as file4:
  print(file4.read())