# -*- coding: utf-8 -*-
"""algoritmavize

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18arUlwBFkrQaXhFkk1dfZYkb_0C111Zz
"""
# Algoritma ve programlama vize ödevi 
# Hayri Doğuhan Korkmaz 2012903058	
import pandas as pd
import numpy as np

x = input("Lütfen İsminizi Giriniz : ")

veri = pd.read_csv("machine.data")

np_veri = np.array(veri)

print(veri.columns)
sözlük = {}            
for i in veri.columns:
    sözlük[i] = input("Lütfen bir değer giriniz : ")
    
print(x,"ödevime baktığın için teşekkür ederim.")
print("Hayri Doğuhan Korkmaz 2012903058")


