# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
from bs4 import BeautifulSoup


url = "https://www.doviz.com/"
response = requests.get(url)
html_icerigi = response.content
soup = BeautifulSoup(html_icerigi,"html.parser")

euro = soup.find("span",{"data-socket-key":"EUR"})
dolar = soup.find("span",{"data-socket-key":"USD"})
altin = soup.find("span",{"data-socket-key":"gram-altin"})

euro = str(euro)
dolar = str(dolar)
altin = str(altin)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 219)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.euro = QtWidgets.QLabel(self.centralwidget)
        self.euro.setGeometry(QtCore.QRect(30, 20, 251, 31))
        self.euro.setObjectName("euro")
        self.dolar = QtWidgets.QLabel(self.centralwidget)
        self.dolar.setGeometry(QtCore.QRect(30, 70, 261, 31))
        self.dolar.setObjectName("dolar")
        self.altin = QtWidgets.QLabel(self.centralwidget)
        self.altin.setGeometry(QtCore.QRect(30, 130, 301, 31))
        self.altin.setObjectName("altin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 351, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.euro.setText(_translate("MainWindow", "Euro : "+ euro))
        self.dolar.setText(_translate("MainWindow", "Amerikan Doları : "+ dolar))
        self.altin.setText(_translate("MainWindow", "Gram Altın : "+ altin))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet("#MainWindow{border-image:url(stonks.jpg)}")
    MainWindow = QtWidgets.QMainWindow()
    app.setWindowIcon(QtGui.QIcon('dolaricon.png'))
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
